//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace ToDoListDataRepository
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Crests>();
                db.CreateTable<CustomerCommunications>();
                db.CreateTable<CustomerEmployees>();
                db.CreateTable<Customers>();
                db.CreateTable<CustomerStores>();
                db.CreateTable<DatabaseVersions>();
                db.CreateTable<EmployeeEmployeeTasks>();
                db.CreateTable<Employees>();
                db.CreateTable<EmployeeTasks>();
                db.CreateTable<Evaluations>();
                db.CreateTable<OrderItems>();
                db.CreateTable<Orders>();
                db.CreateTable<Pictures>();
                db.CreateTable<Probations>();
                db.CreateTable<ProductCatalogs>();
                db.CreateTable<ProductImages>();
                db.CreateTable<Products>();
                db.CreateTable<QuoteItems>();
                db.CreateTable<Quotes>();
                db.CreateTable<States>();
                db.CreateTable<TaskAttachedFiles>();
            }
        }
    }
    public partial class Crests
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public String CityName { get; set; }
        
        public Byte[] SmallImage { get; set; }
        
        public Byte[] LargeImage { get; set; }
        
    }
    
    public partial class CustomerCommunications
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public Int64? EmployeeId { get; set; }
        
        public Int64? CustomerEmployeeId { get; set; }
        
        [NotNull]
        public DateTime Date { get; set; }
        
        public String Type { get; set; }
        
        public String Purpose { get; set; }
        
    }
    
    public partial class CustomerEmployees
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public String FirstName { get; set; }
        
        [NotNull]
        public String LastName { get; set; }
        
        public String FullName { get; set; }
        
        [NotNull]
        public Int32 Prefix { get; set; }
        
        [NotNull]
        public String MobilePhone { get; set; }
        
        [NotNull]
        public String Email { get; set; }
        
        public Int64? PictureId { get; set; }
        
        public Int64? CustomerId { get; set; }
        
        public Int64? CustomerStoreId { get; set; }
        
        public String Position { get; set; }
        
        [NotNull]
        public Boolean IsPurchaseAuthority { get; set; }
        
    }
    
    public partial class Customers
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public String Name { get; set; }
        
        public String HomeOffice_Line { get; set; }
        
        public String HomeOffice_City { get; set; }
        
        public Int32? HomeOffice_State { get; set; }
        
        public Double? HomeOffice_Latitude { get; set; }
        
        public Double? HomeOffice_Longitude { get; set; }
        
        public String HomeOffice_ZipCode { get; set; }
        
        public String BillingAddress_Line { get; set; }
        
        public String BillingAddress_City { get; set; }
        
        public Int32? BillingAddress_State { get; set; }
        
        public Double? BillingAddress_Latitude { get; set; }
        
        public Double? BillingAddress_Longitude { get; set; }
        
        public String BillingAddress_ZipCode { get; set; }
        
        public String HomeOfficeLine { get; set; }
        
        public String HomeOfficeCity { get; set; }
        
        public String HomeOfficeZipCode { get; set; }
        
        public String BillingAddressLine { get; set; }
        
        public String BillingAddressCity { get; set; }
        
        public String BillingAddressZipCode { get; set; }
        
        [NotNull]
        public Int32 HomeOfficeState { get; set; }
        
        [NotNull]
        public Double HomeOfficeLatitude { get; set; }
        
        [NotNull]
        public Double HomeOfficeLongitude { get; set; }
        
        [NotNull]
        public Int32 BillingAddressState { get; set; }
        
        [NotNull]
        public Double BillingAddressLatitude { get; set; }
        
        [NotNull]
        public Double BillingAddressLongitude { get; set; }
        
        public String Phone { get; set; }
        
        public String Fax { get; set; }
        
        public String Website { get; set; }
        
        [NotNull]
        public Decimal AnnualRevenue { get; set; }
        
        [NotNull]
        public Int32 TotalStores { get; set; }
        
        [NotNull]
        public Int32 TotalEmployees { get; set; }
        
        [NotNull]
        public Int32 Status { get; set; }
        
        public String Profile { get; set; }
        
        public Byte[] Logo { get; set; }
        
    }
    
    public partial class CustomerStores
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public Int64? CustomerId { get; set; }
        
        public String Address_Line { get; set; }
        
        public String Address_City { get; set; }
        
        public Int32? Address_State { get; set; }
        
        public Double? Address_Latitude { get; set; }
        
        public Double? Address_Longitude { get; set; }
        
        public String Address_ZipCode { get; set; }
        
        public String Address_Line1 { get; set; }
        
        public String Address_City1 { get; set; }
        
        [NotNull]
        public Int32 Address_State1 { get; set; }
        
        public String Address_ZipCode1 { get; set; }
        
        [NotNull]
        public Double Address_Latitude1 { get; set; }
        
        [NotNull]
        public Double Address_Longitude1 { get; set; }
        
        public String Phone { get; set; }
        
        public String Fax { get; set; }
        
        [NotNull]
        public Int32 TotalEmployees { get; set; }
        
        [NotNull]
        public Int32 SquereFootage { get; set; }
        
        [NotNull]
        public Decimal AnnualSales { get; set; }
        
        public Int64? CrestId { get; set; }
        
        public String Location { get; set; }
        
    }
    
    public partial class DatabaseVersions
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public DateTime Date { get; set; }
        
    }
    
    public partial class EmployeeEmployeeTasks
    {
        [NotNull]
        public Int64 Employee_Id { get; set; }
        
        [NotNull]
        public Int64 EmployeeTask_Id { get; set; }
        
    }
    
    public partial class Employees
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public Int32 Department { get; set; }
        
        [NotNull]
        public String Title { get; set; }
        
        [NotNull]
        public Int32 Status { get; set; }
        
        public DateTime? HireDate { get; set; }
        
        public String PersonalProfile { get; set; }
        
        public Int64? ProbationReason_Id { get; set; }
        
        [NotNull]
        public String FirstName { get; set; }
        
        [NotNull]
        public String LastName { get; set; }
        
        public String FullName { get; set; }
        
        [NotNull]
        public Int32 Prefix { get; set; }
        
        public String HomePhone { get; set; }
        
        [NotNull]
        public String MobilePhone { get; set; }
        
        [NotNull]
        public String Email { get; set; }
        
        public String Skype { get; set; }
        
        public DateTime? BirthDate { get; set; }
        
        public Int64? PictureId { get; set; }
        
        public String Address_Line { get; set; }
        
        public String Address_City { get; set; }
        
        public Int32? Address_State { get; set; }
        
        public Double? Address_Latitude { get; set; }
        
        public Double? Address_Longitude { get; set; }
        
        public String Address_ZipCode { get; set; }
        
        public String AddressLine { get; set; }
        
        public String AddressCity { get; set; }
        
        public String AddressZipCode { get; set; }
        
        [NotNull]
        public Int32 AddressState { get; set; }
        
        [NotNull]
        public Double AddressLatitude { get; set; }
        
        [NotNull]
        public Double AddressLongitude { get; set; }
        
    }
    
    public partial class EmployeeTasks
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public String Subject { get; set; }
        
        public String Description { get; set; }
        
        public String RtfTextDescription { get; set; }
        
        public DateTime? StartDate { get; set; }
        
        public DateTime? DueDate { get; set; }
        
        [NotNull]
        public Int32 Status { get; set; }
        
        [NotNull]
        public Int32 Priority { get; set; }
        
        [NotNull]
        public Int32 Completion { get; set; }
        
        [NotNull]
        public Boolean Reminder { get; set; }
        
        public DateTime? ReminderDateTime { get; set; }
        
        public Int64? AssignedEmployeeId { get; set; }
        
        public Int64? OwnerId { get; set; }
        
        public Int64? CustomerEmployeeId { get; set; }
        
        [NotNull]
        public Int32 FollowUp { get; set; }
        
        [NotNull]
        public Boolean Private { get; set; }
        
        public String Category { get; set; }
        
        [NotNull]
        public Boolean AttachedCollectionsChanged { get; set; }
        
        public Int64? ParentId { get; set; }
        
        public String Predecessors { get; set; }
        
    }
    
    public partial class Evaluations
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public Int64? CreatedById { get; set; }
        
        [NotNull]
        public DateTime CreatedOn { get; set; }
        
        public Int64? EmployeeId { get; set; }
        
        public String Subject { get; set; }
        
        public String Details { get; set; }
        
        [NotNull]
        public Int32 Rating { get; set; }
        
    }
    
    public partial class OrderItems
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public Int64? OrderId { get; set; }
        
        public Int64? ProductId { get; set; }
        
        [NotNull]
        public Int32 ProductUnits { get; set; }
        
        [NotNull]
        public Decimal ProductPrice { get; set; }
        
        [NotNull]
        public Decimal Discount { get; set; }
        
        [NotNull]
        public Decimal Total { get; set; }
        
    }
    
    public partial class Orders
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public String InvoiceNumber { get; set; }
        
        public Int64? CustomerId { get; set; }
        
        public Int64? StoreId { get; set; }
        
        public String PONumber { get; set; }
        
        public Int64? EmployeeId { get; set; }
        
        [NotNull]
        public DateTime OrderDate { get; set; }
        
        [NotNull]
        public Decimal SaleAmount { get; set; }
        
        [NotNull]
        public Decimal ShippingAmount { get; set; }
        
        [NotNull]
        public Decimal TotalAmount { get; set; }
        
        public DateTime? ShipDate { get; set; }
        
        [NotNull]
        public Int32 ShipMethod { get; set; }
        
        public String OrderTerms { get; set; }
        
        [NotNull]
        public Int32 ShipmentCourier { get; set; }
        
        public String ShipmentCourierId { get; set; }
        
        [NotNull]
        public Int32 ShipmentStatus { get; set; }
        
        public String Comments { get; set; }
        
        [NotNull]
        public Decimal RefundTotal { get; set; }
        
        [NotNull]
        public Decimal PaymentTotal { get; set; }
        
    }
    
    public partial class Pictures
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public Byte[] Data { get; set; }
        
    }
    
    public partial class Probations
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public String Reason { get; set; }
        
    }
    
    public partial class ProductCatalogs
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public Int64? ProductId { get; set; }
        
        public Byte[] PDF { get; set; }
        
    }
    
    public partial class ProductImages
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public Int64? PictureId { get; set; }
        
        public Int64? ProductId { get; set; }
        
    }
    
    public partial class Products
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public String Name { get; set; }
        
        public String Description { get; set; }
        
        [NotNull]
        public DateTime ProductionStart { get; set; }
        
        [NotNull]
        public Boolean Available { get; set; }
        
        public Byte[] Image { get; set; }
        
        public Int64? SupportId { get; set; }
        
        public Int64? EngineerId { get; set; }
        
        public Int32? CurrentInventory { get; set; }
        
        [NotNull]
        public Int32 Backorder { get; set; }
        
        [NotNull]
        public Int32 Manufacturing { get; set; }
        
        public Byte[] Barcode { get; set; }
        
        public Int64? PrimaryImageId { get; set; }
        
        [NotNull]
        public Decimal Cost { get; set; }
        
        [NotNull]
        public Decimal SalePrice { get; set; }
        
        [NotNull]
        public Decimal RetailPrice { get; set; }
        
        [NotNull]
        public Double Weight { get; set; }
        
        [NotNull]
        public Double ConsumerRating { get; set; }
        
        [NotNull]
        public Int32 Category { get; set; }
        
    }
    
    public partial class QuoteItems
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public Int64? QuoteId { get; set; }
        
        public Int64? ProductId { get; set; }
        
        [NotNull]
        public Int32 ProductUnits { get; set; }
        
        [NotNull]
        public Decimal ProductPrice { get; set; }
        
        [NotNull]
        public Decimal Discount { get; set; }
        
        [NotNull]
        public Decimal Total { get; set; }
        
    }
    
    public partial class Quotes
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public String Number { get; set; }
        
        public Int64? CustomerId { get; set; }
        
        public Int64? CustomerStoreId { get; set; }
        
        public Int64? EmployeeId { get; set; }
        
        [NotNull]
        public DateTime Date { get; set; }
        
        [NotNull]
        public Decimal SubTotal { get; set; }
        
        [NotNull]
        public Decimal ShippingAmount { get; set; }
        
        [NotNull]
        public Decimal Total { get; set; }
        
        [NotNull]
        public Double Opportunity { get; set; }
        
    }
    
    public partial class States
    {
        [PrimaryKey]
        public Int32 ShortName { get; set; }
        
        public String LongName { get; set; }
        
        public Byte[] Flag48px { get; set; }
        
        public Byte[] Flag24px { get; set; }
        
    }
    
    public partial class TaskAttachedFiles
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public Int64? EmployeeTaskId { get; set; }
        
        public String Name { get; set; }
        
        public Byte[] Content { get; set; }
        
    }
    
}
